#pragma config(Sensor, S1,     motorTouch,     sensorTouch)
#pragma config(Motor,  motorA,          leftWheel,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightWheel,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          letters,       tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

void wheels () {
		motor[motorA] = joystick.joy1_y1;
	motor[motorB] = joystick.joy1_y2;
}


task main()
{
	bool humancontrol = true;
	while(true){
	getJoystickSettings(joystick);

	if(humancontrol) {
		wheels();
	}

	if(SensorValue[motorTouch]==1 || joy1Btn(Btn2)==1) {
		motor[letters] = 50;
		motor[rightWheel] = 0;
		motor[leftWheel] = 0;
		wait1Msec(750);
		motor[letters] = -50;
		wait1Msec(2000);
		motor[letters]=0;
	}

}
}
